version: "3"
services:
  exercise4:
    build: ./service/.
    ports:
     - "9003:9003"
    depends_on:
      - mongodb
    command: ["./wait-for-it.sh", "mongodb:27027","-t","5", "--","node", "app.js"]
  messageapp:
    image: cabify/backend-bootcamp-messageapp
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27018:27017
  mongodb-2:
    image: mongo
    volumes:
      - ./data2/db2:/data/db
    ports:
      - 27019:27017
